### PR TITLE
Pre-Build raylib

### PR DESCRIPTION
**Pull request by JeremyGrosser**

### CODE REVIEW

**Comment by mgrojo** [comment]
This will fail unless `git submodule update  --init` has been executed, or it was cloned with `git clone --recurse-submodules`.

**Comment by Fabien-Chouteau** [comment]
Thanks @JeremyGrosser 

I am not sure this is the right way to do since some distrib provide raylib binaries.

**Comment by JeremyGrosser** [comment]
If you’d prefer to use an external system package instead that works for me. Thanks for taking a look.

**Comment by Fabien-Chouteau** [comment]
What's weird is that I can see Raylib packages for msys2, homebrew, arch, fedora, but not Ubuntu/Debian...

Ubuntu is probably the most used distrib among Alire users, so this is kind of bad.

**Comment by JeremyGrosser** [comment]
I got the impression from tsoding that most people just statically link it.

**Pull request closed without merging**
